### ISSUE TITLE
Allow comment lines

### ISSUE THREAD

**Issue by mzeis** [staempfli/symlinker-pro#1]
It would be great to allow single line comments. E.g. ignore all lines starting with `#`. What do you think about this feature?

Thanks for your great tool!

**Comment by jalogut** [comment]
Hi @mzeis 

I am glad you like the tool. Yes, I think it would be a good feature to add. Unfortunately I am a bit busy atm. If you want to create a PR, I'd really appreciate it.

**Comment by mzeis** [comment]
HI @jalogut,

I'm sorry but we decided to not use symlinker-pro for now (turns out we don't have so many symlinks to manage and we'll go with a more bare-bone approach). Still, I'd recommend everybody to consider it for their workflow!

You can close the issue or keep it open in case somebody else (or future me) has time to pick this up.

**Comment by jalogut** [comment]
Hi @mzeis,

Thanks for the update. I’ll close that for now then.
